version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - run:
          name: Build Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t clarkzjw/yulubot:$TAG .
